// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Lieferliste_WPF.Data;
using Lieferliste_WPF.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Lieferliste_WPF.Data.Configurations
{
    public partial class RessourceConfiguration : IEntityTypeConfiguration<Ressource>
    {
        public void Configure(EntityTypeBuilder<Ressource> entity)
        {
            entity.Property(e => e.WorkSapId).IsUnicode(false);

            entity.HasOne(d => d.WorkArea)
                .WithMany(p => p.Ressources)
                .HasForeignKey(d => d.WorkAreaId)
                .HasConstraintName("FK_Ressource_WorkArea");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Ressource> entity);
    }
}
