// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Lieferliste_WPF.Data;
using Lieferliste_WPF.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Lieferliste_WPF.Data.Configurations
{
    public partial class TblArbeitsplatzZuteilungConfiguration : IEntityTypeConfiguration<TblArbeitsplatzZuteilung>
    {
        public void Configure(EntityTypeBuilder<TblArbeitsplatzZuteilung> entity)
        {
            entity.Property(e => e.Arbid).IsUnicode(false);

            entity.HasOne(d => d.BidNavigation)
                .WithMany(p => p.TblArbeitsplatzZuteilungs)
                .HasForeignKey(d => d.Bid)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_tblArbeitsplatzZuteilung_tblbereich");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TblArbeitsplatzZuteilung> entity);
    }
}
