// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Lieferliste_WPF.Data;
using Lieferliste_WPF.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Lieferliste_WPF.Data.Configurations
{
    public partial class TblAbfrageblattConfiguration : IEntityTypeConfiguration<TblAbfrageblatt>
    {
        public void Configure(EntityTypeBuilder<TblAbfrageblatt> entity)
        {
            entity.Property(e => e.Aid).IsUnicode(false);

            entity.HasOne(d => d.Aba)
                .WithMany(p => p.TblAbfrageblatts)
                .HasForeignKey(d => d.Abaid)
                .HasConstraintName("FK_tblAbfrageblatt_tblAbfrageblattAuswahl");

            entity.HasOne(d => d.AidNavigation)
                .WithMany(p => p.TblAbfrageblatts)
                .HasForeignKey(d => d.Aid)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_tblAbfrageblatt_tblAuftrag");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TblAbfrageblatt> entity);
    }
}
