// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Lieferliste_WPF.Data;
using Lieferliste_WPF.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Lieferliste_WPF.Data.Configurations
{
    public partial class TblAuftragConfiguration : IEntityTypeConfiguration<TblAuftrag>
    {
        public void Configure(EntityTypeBuilder<TblAuftrag> entity)
        {
            entity.Property(e => e.Aid).IsUnicode(false);

            entity.Property(e => e.DummyMat).IsUnicode(false);

            entity.HasOne(d => d.DummyMatNavigation)
                .WithMany(p => p.TblAuftrags)
                .HasForeignKey(d => d.DummyMat)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_tblAuftrag_tblDummy1");

            entity.HasOne(d => d.MaterialNavigation)
                .WithMany(p => p.TblAuftrags)
                .HasForeignKey(d => d.Material)
                .HasConstraintName("FK_tblAuftrag_tblMaterial");

            entity.HasOne(d => d.Pro)
                .WithMany(p => p.TblAuftrags)
                .HasForeignKey(d => d.ProId)
                .HasConstraintName("FK_tblAuftrag_tblProjekt");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TblAuftrag> entity);
    }
}
