// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Lieferliste_WPF.Data;
using Lieferliste_WPF.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Lieferliste_WPF.Data.Configurations
{
    public partial class TblEinstellTeilConfiguration : IEntityTypeConfiguration<TblEinstellTeil>
    {
        public void Configure(EntityTypeBuilder<TblEinstellTeil> entity)
        {
            entity.Property(e => e.DummyMat).IsUnicode(false);

            entity.HasOne(d => d.DummyMatNavigation)
                .WithMany(p => p.TblEinstellTeils)
                .HasForeignKey(d => d.DummyMat)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_tblEinstellTeil_tblDummy");

            entity.HasOne(d => d.TtnrNavigation)
                .WithMany(p => p.TblEinstellTeils)
                .HasForeignKey(d => d.Ttnr)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_tblEinstellTeil_tblMaterial");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TblEinstellTeil> entity);
    }
}
