// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Lieferliste_WPF.Data;
using Lieferliste_WPF.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Lieferliste_WPF.Data.Configurations
{
    public partial class TblRessKappaConfiguration : IEntityTypeConfiguration<TblRessKappa>
    {
        public void Configure(EntityTypeBuilder<TblRessKappa> entity)
        {
            entity.Property(e => e.Id).HasComment("Identity");

            entity.Property(e => e.Created).HasComment("Timestamp to create the Datarow");

            entity.Property(e => e.End1).HasComment("Ende Schicht 1");

            entity.Property(e => e.End2).HasComment("Ende Schicht");

            entity.Property(e => e.End3).HasComment("Ende Schicht 3");

            entity.Property(e => e.Rid).HasComment("Resource ID");

            entity.Property(e => e.Start1).HasComment("Start Schicht 1");

            entity.Property(e => e.Start2).HasComment("Start Schicht 2");

            entity.Property(e => e.Start3).HasComment("Start Schicht 3");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TblRessKappa> entity);
    }
}
