// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Lieferliste_WPF.Data;
using Lieferliste_WPF.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Lieferliste_WPF.Data.Configurations
{
    public partial class UserCostConfiguration : IEntityTypeConfiguration<UserCost>
    {
        public void Configure(EntityTypeBuilder<UserCost> entity)
        {
            entity.HasKey(e => new { e.UsrIdent, e.CostId });

            entity.HasOne(d => d.Cost)
                .WithMany(p => p.UserCosts)
                .HasForeignKey(d => d.CostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserCost_Costunit");

            entity.HasOne(d => d.UsrIdentNavigation)
                .WithMany(p => p.UserCosts)
                .HasForeignKey(d => d.UsrIdent)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_User_UserCost");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UserCost> entity);
    }
}
