// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class AccountWorkArea
{
    public string AccountId { get; set; } = null!;

    public int WorkAreaId { get; set; }

    public DateTime Created { get; set; }

    public bool FullAccess { get; set; }

    public bool Standard { get; set; }

    public virtual IdmAccount Account { get; set; } = null!;

    public virtual WorkArea WorkArea { get; set; } = null!;
}