// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class AccountVorgang
{
    public string AccountId { get; set; } = null!;

    public string VorgangId { get; set; } = null!;

    public DateTime Created { get; set; }

    public virtual IdmAccount Account { get; set; } = null!;

    public virtual Vorgang Vorgang { get; set; } = null!;
}