// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class Component
{
    public string TtnrC { get; set; } = null!;

    public string? Description { get; set; }

    public virtual ICollection<MaterialComponent> MaterialComponents { get; set; } = new List<MaterialComponent>();
}