// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class EmployeeNote
{
    public int Id { get; set; }

    public string AccId { get; set; } = null!;

    public string Reference { get; set; } = null!;

    public string? Comment { get; set; }

    public DateTime Date { get; set; }

    public DateTime Timestamp { get; set; }

    public double? Processingtime { get; set; }

    public virtual IdmAccount Acc { get; set; } = null!;
}