// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class IdmRelation
{
    public long RoleId { get; set; }

    public string AccountId { get; set; } = null!;

    public DateTime? Lastmodified { get; set; }

    public virtual IdmAccount Account { get; set; } = null!;

    public virtual IdmRole Role { get; set; } = null!;
}