// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class InMemoryOnline
{
    public int OnlId { get; set; }

    public string Userid { get; set; } = null!;

    public string PcId { get; set; } = null!;

    public DateTime Login { get; set; }

    public virtual ICollection<InMemoryMsg> InMemoryMsgs { get; set; } = new List<InMemoryMsg>();
}