// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class InMemoryOnline
{
    public int OnlId { get; set; }

    public string? Userid { get; set; }

    public string? PcId { get; set; }

    public DateTime Login { get; set; }

    public DateTime? LifeTime { get; set; }
}