// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace El2Core.Models
{
    public partial class MachPlanVorgangsProcResult
    {
        [StringLength(255)]
        public string VorgangID { get; set; } = default!;
        [StringLength(50)]
        public string AID { get; set; } = default!;
        public short VNR { get; set; }
        [StringLength(255)]
        public string? ArbPlSAP { get; set; }
        [StringLength(150)]
        public string? Text { get; set; }
        public DateTime? SpaetStart { get; set; }
        public DateTime? SpaetEnd { get; set; }
        public float? BEAZE { get; set; }
        public float? RSTZE { get; set; }
        public float? WRTZE { get; set; }
        [StringLength(5)]
        public string? BEAZE_Einheit { get; set; }
        [StringLength(5)]
        public string? RSTZE_Einheit { get; set; }
        [StringLength(5)]
        public string? WRTZE_Einheit { get; set; }
        [StringLength(255)]
        public string? SysStatus { get; set; }
        [StringLength(255)]
        public string? SteuSchl { get; set; }
        [StringLength(255)]
        public string? BasisMg { get; set; }
        public DateTime? Termin { get; set; }
        [StringLength(2147483647)]
        public string? Bem_M { get; set; }
        [StringLength(2147483647)]
        public string? Bem_T { get; set; }
        [StringLength(2147483647)]
        public string? Bem_MA { get; set; }
        public bool aktuell { get; set; }
        [Column("Quantity-scrap")]
        public int? Quantityscrap { get; set; }
        [Column("Quantity-yield")]
        public int? Quantityyield { get; set; }
        [Column("Quantity-miss")]
        public int? Quantitymiss { get; set; }
        public string? ProcessingUOM { get; set; }
        public float? ProcessTime { get; set; }
        [Column("Quantity-rework")]
        public int? Quantityrework { get; set; }
        public bool Visability { get; set; }
        public DateTime? ActualStartDate { get; set; }
        public DateTime? ActualEndDate { get; set; }
        [StringLength(9)]
        public string? Bullet { get; set; }
        public int? SPOS { get; set; }
        public int? RID { get; set; }
        [StringLength(2147483647)]
        public string? CommentMach { get; set; }
        [StringLength(9)]
        public string? BulletTwo { get; set; }
        [StringLength(50)]
        public string? MarkCode { get; set; }
        public DateTime? KlimaPrint { get; set; }
        public float? Correction { get; set; }
        [Column("Quantity-miss-neo")]
        public int? Quantitymissneo { get; set; }
        public string? SortPos { get; set; }
        [Column("MSF-InWork")]
        public bool MSFInWork { get; set; }
        [StringLength(50)]
        public string? MSF { get; set; }
        [StringLength(80)]
        public string AccountId { get; set; } = default!;
    }
}
