// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Utilities.Models;

public partial class Machine
{
    public int MaId { get; set; }

    public string? MaName { get; set; }

    public string? MaArt { get; set; }

    public string? InventNo { get; set; }

    public int? CostUnit { get; set; }

    public virtual Costunit? CostUnitNavigation { get; set; }
}