// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class MeasureRessRessource
{
    public int MessRid { get; set; }

    public int Rid { get; set; }

    public virtual MeasureRess MessR { get; set; } = null!;

    public virtual Ressource RidNavigation { get; set; } = null!;
}