// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class MeasureRess
{
    public int MessRid { get; set; }

    public string? UserId { get; set; }

    public int? Rid { get; set; }

    public virtual ICollection<MeasureRessRessource> MeasureRessRessources { get; set; } = new List<MeasureRessRessource>();

    public virtual ICollection<MeasureRessVorgang> MeasureRessVorgangs { get; set; } = new List<MeasureRessVorgang>();

    public virtual IdmAccount? User { get; set; }
}