// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class Online
{
    public int Oid { get; set; }

    public string UserId { get; set; } = null!;

    public string PcId { get; set; } = null!;

    public DateTime Login { get; set; }
}