// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class OrderDocu
{
    public string OrderId { get; set; } = null!;

    public string? VmpbTemplate { get; set; }

    public string? VmpbOriginal { get; set; }

    public bool? InWork { get; set; }

    public virtual OrderRb Order { get; set; } = null!;
}