// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace El2Utilities.Models;

public partial class PermissionRoles
{
    public DateTime Created { get; set; }

    public int RoleKey { get; set; }

    public string PermissionKey { get; set; }

    public virtual Permission PermissionKeyNavigation { get; set; }

    public virtual Roles RoleKeyNavigation { get; set; }
}