// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class ProductionOrderFilter
{
    public string OrderNumber { get; set; } = null!;

    public string? Kommentar { get; set; }

    public DateTime? ZeitStempelÄnderung { get; set; }
}