// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class Response
{
    public long ResponseId { get; set; }

    public string VorgangId { get; set; } = null!;

    public int Yield { get; set; }

    public int Rework { get; set; }

    public int Scrap { get; set; }

    public DateTime Timestamp { get; set; }

    public bool? Notreal { get; set; }

    public virtual Vorgang Vorgang { get; set; } = null!;
}