// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class Ressource
{
    public int RessourceId { get; set; }

    public string? RessName { get; set; }

    public string? Abteilung { get; set; }

    public string? Info { get; set; }

    public string? Inventarnummer { get; set; }

    public int? Sort { get; set; }

    public int? Type { get; set; }

    public int? WorkAreaId { get; set; }

    public virtual ICollection<RessourceCostUnit> RessourceCostUnits { get; set; } = new List<RessourceCostUnit>();

    public virtual ICollection<RessourceUser> RessourceUsers { get; set; } = new List<RessourceUser>();

    public virtual ICollection<Vorgang> Vorgangs { get; set; } = new List<Vorgang>();

    public virtual WorkArea? WorkArea { get; set; }

    public virtual ICollection<WorkSap> WorkSaps { get; set; } = new List<WorkSap>();
}