// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace El2Utilities.Models;

public partial class Roles
{
    public int Id { get; set; }

    public string Description { get; set; }

    /// <summary>
    /// Time of Create
    /// </summary>
    public DateTime Created { get; set; }

    public int? Rolelevel { get; set; }

    public virtual ICollection<PermissionRoles> PermissionRoles { get; set; } = new List<PermissionRoles>();

    public virtual ICollection<User> UserIdent { get; set; } = new List<User>();
}