// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class Rule
{
    public int RuleId { get; set; }

    public string RuleName { get; set; } = null!;

    public string RuleValue { get; set; } = null!;

    public string? RuleData { get; set; }
}