// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class ShiftCalendarShiftPlan
{
    public int CalId { get; set; }

    public int PlanId { get; set; }

    public DateTime Timestamp { get; set; }

    public string? YearKw { get; set; }

    public virtual ShiftCalendar Cal { get; set; } = null!;

    public virtual ShiftPlan Plan { get; set; } = null!;
}