// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class ShiftPlan
{
    public int Id { get; set; }

    public string PlanName { get; set; } = null!;

    public byte[]? Sun { get; set; }

    public byte[]? Mon { get; set; }

    public byte[]? Tue { get; set; }

    public byte[]? Wed { get; set; }

    public byte[]? Thu { get; set; }

    public byte[]? Fre { get; set; }

    public byte[]? Sat { get; set; }
}