// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class ShiftCover
{
    public int Id { get; set; }

    public string CoverName { get; set; } = null!;

    public byte[]? CoverMask { get; set; }
}