// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Utilities.Models;

public partial class TblProjekt
{
    public int Pid { get; set; }

    public string? Projekt { get; set; }

    public string? Projektinfo { get; set; }

    public string? ProjektFarbe { get; set; }

    public string? ProjektArt { get; set; }

    public virtual ICollection<TblAuftrag> TblAuftrags { get; set; } = new List<TblAuftrag>();
}