// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class User
{
    public string UserIdent { get; set; } = null!;

    public int? Personalnumber { get; set; }

    public string UsrName { get; set; } = null!;

    public string? UsrGroup { get; set; }

    public string? UsrRegion { get; set; }

    public string? UsrEmail { get; set; }

    public string? UsrInfo { get; set; }

    public bool? Exited { get; set; }

    public virtual ICollection<RessourceUser> RessourceUsers { get; set; } = new List<RessourceUser>();

    public virtual ICollection<UserCost> UserCosts { get; set; } = new List<UserCost>();

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();

    public virtual ICollection<UserVorgang> UserVorgangs { get; set; } = new List<UserVorgang>();

    public virtual ICollection<UserWorkArea> UserWorkAreas { get; set; } = new List<UserWorkArea>();
}