// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class UserVorgang
{
    public string UserId { get; set; } = null!;

    public string Vid { get; set; } = null!;

    public DateTime? Timestamp { get; set; }

    public virtual User User { get; set; } = null!;

    public virtual Vorgang VidNavigation { get; set; } = null!;
}