// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class VorgangComponent
{
    public int CompId { get; set; }

    public string Material { get; set; } = null!;

    public string Vorgang { get; set; } = null!;

    public int? RequirementQuantity { get; set; }

    public int? QuantityWithdrawn { get; set; }

    public int? ConfirmedQuantity { get; set; }

    public DateTime? LatestRequirementsDate { get; set; }

    public virtual TblMaterial MaterialNavigation { get; set; } = null!;

    public virtual Vorgang VorgangNavigation { get; set; } = null!;
}