// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class VorgangDocu
{
    public string VorgangId { get; set; } = null!;

    public string? VmpbTemplate { get; set; }

    public string? VmpbOriginal { get; set; }

    public int InWorkState { get; set; }

    public virtual Vorgang Vorgang { get; set; } = null!;
}