// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class WorkArea
{
    public int WorkAreaId { get; set; }

    public string? Bereich { get; set; }

    public string? Info { get; set; }

    public byte Sort { get; set; }

    public bool IsLocked { get; set; }

    public bool CreateFolder { get; set; }

    public virtual ICollection<Ressource> Ressources { get; set; } = new List<Ressource>();

    public virtual ICollection<UserWorkArea> UserWorkAreas { get; set; } = new List<UserWorkArea>();
}