// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace El2Utilities.Models;

public partial class WorkArea
{
    public int WorkAreaId { get; set; }

    public string Bereich { get; set; }

    public string Abteilung { get; set; }

    public byte? Sort { get; set; }

    public virtual ICollection<User> User { get; set; } = new List<User>();
}