//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lieferliste_WPF.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EntitiesAlloc : DbContext
    {
        public EntitiesAlloc()
            : base("name=EntitiesAlloc")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblArbeitsplatzZuteilung> tblArbeitsplatzZuteilung { get; set; }
        public virtual DbSet<tblAuftrag> tblAuftrag { get; set; }
        public virtual DbSet<tblDummy> tblDummy { get; set; }
        public virtual DbSet<tblMaterial> tblMaterial { get; set; }
        public virtual DbSet<tblRessKappa> tblRessKappa { get; set; }
        public virtual DbSet<tblRessource> tblRessource { get; set; }
        public virtual DbSet<tblRessourceVorgang> tblRessourceVorgang { get; set; }
        public virtual DbSet<tblVorgang> tblVorgang { get; set; }
        public virtual DbSet<RessourceAllocation> RessourceAllocation { get; set; }
        public virtual DbSet<RessZuteilView> RessZuteilView { get; set; }
    
        public virtual ObjectResult<OrderList_Result> OrderList(string aID)
        {
            var aIDParameter = aID != null ?
                new ObjectParameter("AID", aID) :
                new ObjectParameter("AID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OrderList_Result>("OrderList", aIDParameter);
        }
    }
}
