//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lieferliste_WPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class lieferliste
    {
        public string AID { get; set; }
        public string AuftragFarbe { get; set; }
        public bool Dringend { get; set; }
        public string Bemerkung { get; set; }
        public string Prio { get; set; }
        public string LieferTermin { get; set; }
        public string Text { get; set; }
        public string SysStatus { get; set; }
        public Nullable<short> VNR { get; set; }
        public Nullable<System.DateTime> SpaetEnd { get; set; }
        public string VID { get; set; }
        public bool Mappe { get; set; }
        public string Projekt { get; set; }
        public string Projektinfo { get; set; }
        public string ProjektFarbe { get; set; }
        public string ArbBereich { get; set; }
        public Nullable<int> ArbBID { get; set; }
        public string ArbPlSAP { get; set; }
        public Nullable<int> PID { get; set; }
        public Nullable<System.DateTime> SpaetStart { get; set; }
        public bool fertig { get; set; }
        public string Arbeitsplatz { get; set; }
        public Nullable<int> RID { get; set; }
        public string RessName { get; set; }
        public string AuftragArt { get; set; }
        public bool abgeschlossen { get; set; }
        public string ProjektArt { get; set; }
        public string Material { get; set; }
        public string Teil { get; set; }
        public string Plantermin { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Quantity_yield { get; set; }
        public string marker { get; set; }
        public string Bem_M { get; set; }
        public string Bem_T { get; set; }
        public string Bem_MA { get; set; }
        public Nullable<System.DateTime> Termin { get; set; }
        public Nullable<int> Quantity_miss { get; set; }
        public Nullable<int> Quantity_scrap { get; set; }
        public Nullable<int> Quantity_rework { get; set; }
        public Nullable<bool> ausgebl { get; set; }
        public Nullable<float> ProcessTime { get; set; }
    }
}
