//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lieferliste_WPF.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesPermiss : DbContext
    {
        public EntitiesPermiss()
            : base("name=EntitiesPermiss")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PermissionRoles> PermissionRoles { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Permissions> tblBerechtigung { get; set; }
        public virtual DbSet<tblUserListe> tblUserListe { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
    }
}
