//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lieferliste_WPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionRoles
    {
        public int id { get; set; }
        public System.DateTime created { get; set; }
        public string UserKey { get; set; }
        public int RoleKey { get; set; }
        public string PermissionKey { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Permissions tblBerechtigung { get; set; }
    }
}
