//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lieferliste_WPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionRoles
    {
        public int id { get; set; }
        public System.DateTime created { get; set; }
        public string UserKey { get; set; }
        public int RoleKey { get; set; }
        public string PermissionKey { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual tblBerechtigung tblBerechtigung { get; set; }
    }
}
