//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lieferliste_WPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perspective
    {
        public int PerspectID { get; set; }
        public string PerspectName { get; set; }
        public Nullable<byte> PerspectType { get; set; }
        public string PerspectFileName { get; set; }
    }
}
