//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lieferliste_WPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RessZuteilView
    {
        public Nullable<int> RID { get; set; }
        public Nullable<int> BID { get; set; }
        public string ARBID { get; set; }
        public string Bezeichnung { get; set; }
        public string RessName { get; set; }
        public string Info { get; set; }
        public string Inventarnummer { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> ARBZUTID { get; set; }
        public string Bereich { get; set; }
        public string Abteilung { get; set; }
        public Nullable<byte> SORT { get; set; }
        public string Material { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<short> SPOS { get; set; }
        public Nullable<float> korrect { get; set; }
        public string VID { get; set; }
        public Nullable<short> VNR { get; set; }
        public string Text { get; set; }
        public Nullable<float> BEAZE { get; set; }
        public Nullable<System.DateTime> SpaetEnd { get; set; }
        public string Bem_M { get; set; }
        public string Bem_T { get; set; }
        public string Bem_MA { get; set; }
        public Nullable<int> Quantity_scrap { get; set; }
        public Nullable<int> Quantity_yield { get; set; }
        public Nullable<int> Quantity_miss { get; set; }
        public Nullable<float> ProcessTime { get; set; }
        public Nullable<int> Quantity_rework { get; set; }
        public Nullable<int> VGRID { get; set; }
        public string AID { get; set; }
        public string MaterialDescription { get; set; }
    }
}
