//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lieferliste_WPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArbeitsplatzZuteilung
    {
        public int ARBZUTID { get; set; }
        public Nullable<int> RID { get; set; }
        public string ARBID { get; set; }
        public Nullable<int> BID { get; set; }
        public string ZutName { get; set; }
        public Nullable<int> Sortiernummer { get; set; }
    
        public virtual tblRessource tblRessource { get; set; }
    }
}
