//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lieferliste_WPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAuftrag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAuftrag()
        {
            this.tblVorgang = new HashSet<tblVorgang>();
        }
    
        public string AID { get; set; }
        public Nullable<System.DateTime> Eckstart { get; set; }
        public Nullable<System.DateTime> Eckende { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string AuftragFarbe { get; set; }
        public string Material { get; set; }
        public string DummyMat { get; set; }
        public Nullable<int> ProID { get; set; }
        public Nullable<System.DateTime> Iststart { get; set; }
        public Nullable<System.DateTime> Istende { get; set; }
        public string LieferTermin { get; set; }
        public bool abgeschlossen { get; set; }
        public string Prio { get; set; }
        public bool fertig { get; set; }
        public bool Dringend { get; set; }
        public string Bemerkung { get; set; }
        public string SysStatus { get; set; }
        public string AuftragArt { get; set; }
        public bool ausgebl { get; set; }
        public bool Mappe { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual tblDummy tblDummy { get; set; }
        public virtual tblMaterial tblMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVorgang> tblVorgang { get; set; }
    }
}
