//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lieferliste_WPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRessourceVorgang
    {
        public int VGRID { get; set; }
        public Nullable<int> RID { get; set; }
        public string VID { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string usr { get; set; }
        public Nullable<short> SPOS { get; set; }
        public Nullable<short> KW { get; set; }
        public Nullable<float> korrect { get; set; }
        public Nullable<System.DateTime> DateCalculated { get; set; }
    
        public virtual tblRessource tblRessource { get; set; }
        public virtual tblVorgang tblVorgang { get; set; }
    }
}
