//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lieferliste_WPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRessKappa
    {
        public int ID { get; set; }
        public int RID { get; set; }
        public System.DateTime Datum { get; set; }
        public Nullable<int> start1 { get; set; }
        public Nullable<int> end1 { get; set; }
        public string comment1 { get; set; }
        public Nullable<int> start2 { get; set; }
        public Nullable<int> end2 { get; set; }
        public string comment2 { get; set; }
        public Nullable<int> start3 { get; set; }
        public Nullable<int> end3 { get; set; }
        public string comment3 { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
    }
}
