//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lieferliste_WPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserListe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUserListe()
        {
            this.UserRoles = new HashSet<UserRoles>();
        }
    
        public string Name { get; set; }
        public string Personalnummer { get; set; }
        public string UserIdent { get; set; }
        public Nullable<int> Gruppe { get; set; }
        public Nullable<int> Bereich { get; set; }
        public string Email { get; set; }
        public string Info { get; set; }
        public bool info_anzeigen { get; set; }
        public bool exited { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRoles> UserRoles { get; set; }
    }
}
