//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lieferliste_WPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVorgang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVorgang()
        {
            this.tblRessourceVorgang = new HashSet<tblRessourceVorgang>();
        }
    
        public string VID { get; set; }
        public string AID { get; set; }
        public Nullable<short> VNR { get; set; }
        public Nullable<int> BID { get; set; }
        public string ArbPlSAP { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> SpaetStart { get; set; }
        public Nullable<System.DateTime> SpaetEnd { get; set; }
        public Nullable<float> BEAZE { get; set; }
        public Nullable<float> RSTZE { get; set; }
        public Nullable<float> WRTZE { get; set; }
        public string BEAZE_Einheit { get; set; }
        public string RSTZE_Einheit { get; set; }
        public string WRTZE_Einheit { get; set; }
        public string SysStatus { get; set; }
        public string SteuSchl { get; set; }
        public string BasisMg { get; set; }
        public Nullable<System.DateTime> Termin { get; set; }
        public string Bem_M { get; set; }
        public string Bem_T { get; set; }
        public string Bem_MA { get; set; }
        public bool aktuell { get; set; }
        public Nullable<int> Quantity_scrap { get; set; }
        public Nullable<int> Quantity_yield { get; set; }
        public Nullable<int> Quantity_miss { get; set; }
        public string marker { get; set; }
        public string ProcessingUOM { get; set; }
        public Nullable<float> ProcessTime { get; set; }
        public Nullable<int> Quantity_rework { get; set; }
        public bool ausgebl { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
    
        public virtual tblAuftrag tblAuftrag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRessourceVorgang> tblRessourceVorgang { get; set; }
    }
}
