// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Statics.Models;

public partial class Costunit
{
    public int CostunitId { get; set; }

    public string Description { get; set; }

    public bool PlanRelevance { get; set; }

    public virtual ICollection<User> UsrIdent { get; set; } = new List<User>();
}