// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Statics.Models;

public partial class User
{
    public string UserIdent { get; set; }

    public int? Personalnumber { get; set; }

    public string UsrName { get; set; }

    public string UsrGroup { get; set; }

    public string UsrRegion { get; set; }

    public string UsrEmail { get; set; }

    public string UsrInfo { get; set; }

    public bool? Exited { get; set; }

    public virtual ICollection<Costunit> Cost { get; set; } = new List<Costunit>();

    public virtual ICollection<Roles> Role { get; set; } = new List<Roles>();

    public virtual ICollection<WorkArea> WorkArea { get; set; } = new List<WorkArea>();
}