//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lieferliste_WPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("229, 220, 220")]
        public global::System.Drawing.Color Pause {
            get {
                return ((global::System.Drawing.Color)(this["Pause"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("58, 94, 218")]
        public global::System.Drawing.Color Stripe1 {
            get {
                return ((global::System.Drawing.Color)(this["Stripe1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("58, 161, 86")]
        public global::System.Drawing.Color Stripe2 {
            get {
                return ((global::System.Drawing.Color)(this["Stripe2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color outOfDate {
            get {
                return ((global::System.Drawing.Color)(this["outOfDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color inDate {
            get {
                return ((global::System.Drawing.Color)(this["inDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 0")]
        public global::System.Drawing.Color Stripe3 {
            get {
                return ((global::System.Drawing.Color)(this["Stripe3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HL0VSQL02.emea.bosch.com;Initial Catalog=DB_COS_LIEFERLISTE_SQL;Integ" +
            "rated Security=True")]
        public string DBOConnectionString {
            get {
                return ((string)(this["DBOConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-88O2DD0;Initial Catalog=DB_COS_LIEFERLISTE_SQL;Integrated Sec" +
            "urity=True")]
        public string DB_COS_LIEFERLISTE_SQLConnectionString {
            get {
                return ((string)(this["DB_COS_LIEFERLISTE_SQLConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>#FFAA00</string>
  <string>#AAAA00</string>
  <string>#92a8d1</string>
  <string>#034f84</string>
  <string>#f7cac9</string>
  <string>#f7786b</string>
  <string>#deeaee</string>
  <string>#b1cbbb</string>
  <string>#eea29a</string>
  <string>#c94c4c</string>
  <string>#ffef96</string>
  <string>#80ced6</string>
  <string>#4040a1</string>
  <string>#b0aac0</string>
  <string>#009933</string>
  <string>#990000</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ColorPallette {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColorPallette"]));
            }
        }
    }
}
