// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Lieferliste_WPF.Data;
using Lieferliste_WPF.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Lieferliste_WPF.Data.Configurations
{
    public partial class OnlineConfiguration : IEntityTypeConfiguration<Online>
    {
        public void Configure(EntityTypeBuilder<Online> entity)
        {
            entity.Property(e => e.Login).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.PcId).IsFixedLength();

            entity.Property(e => e.UserId).IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Online> entity);
    }
}
