// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Lieferliste_WPF.Data;
using Lieferliste_WPF.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Lieferliste_WPF.Data.Configurations
{
    public partial class TblAbfrageblattAuswahlConfiguration : IEntityTypeConfiguration<TblAbfrageblattAuswahl>
    {
        public void Configure(EntityTypeBuilder<TblAbfrageblattAuswahl> entity)
        {
            entity.Property(e => e.Timestamp).HasDefaultValueSql("(getdate())");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TblAbfrageblattAuswahl> entity);
    }
}
