// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Lieferliste_WPF.Data;
using Lieferliste_WPF.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Lieferliste_WPF.Data.Configurations
{
    public partial class TblDummyConfiguration : IEntityTypeConfiguration<TblDummy>
    {
        public void Configure(EntityTypeBuilder<TblDummy> entity)
        {
            entity.HasKey(e => e.Aid)
                .HasName("PK_tblDummy_1");

            entity.Property(e => e.Aid).IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TblDummy> entity);
    }
}
