// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Lieferliste_WPF.Data;
using Lieferliste_WPF.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Lieferliste_WPF.Data.Configurations
{
    public partial class VorgangConfiguration : IEntityTypeConfiguration<Vorgang>
    {
        public void Configure(EntityTypeBuilder<Vorgang> entity)
        {
            entity.Property(e => e.VorgangId).IsUnicode(false);

            entity.Property(e => e.Aid).IsUnicode(false);

            entity.Property(e => e.ArbPlSap).IsUnicode(false);

            entity.Property(e => e.BemM).IsUnicode(false);

            entity.Property(e => e.BemMa).IsUnicode(false);

            entity.Property(e => e.BemT).IsUnicode(false);

            entity.Property(e => e.CommentMach).IsUnicode(false);

            entity.Property(e => e.Marker).IsFixedLength();

            entity.Property(e => e.ProcessingUom).IsFixedLength();

            entity.HasOne(d => d.AidNavigation)
                .WithMany(p => p.Vorgangs)
                .HasForeignKey(d => d.Aid)
                .HasConstraintName("FK_tblVorgang_tblAuftrag");

            entity.HasOne(d => d.ArbPlSapNavigation)
                .WithMany(p => p.Vorgangs)
                .HasForeignKey(d => d.ArbPlSap)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_Vorgang_WorkSap");

            entity.HasOne(d => d.RidNavigation)
                .WithMany(p => p.Vorgangs)
                .HasForeignKey(d => d.Rid)
                .HasConstraintName("FK_Vorgang_Ressource");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Vorgang> entity);
    }
}
